jobs:
  build:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: mvn clean install
      - run:
          name: Run Application
          command: 
            sudo java -jar /home/circleci/.m2/repository/com/webomates/test/0.0.1-SNAPSHOT/test-0.0.1-SNAPSHOT.jar
