jobs:
  build:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: mvn clean install
      - run:
          name: Run Application
          command: |
            sudo java -jar /home/circleci/project/target/test-0.0.1-SNAPSHOT.jar
            echo ${username}
