jobs:
  build:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run:
          name: Run Application
          command: 
            sudo java -jar https://s3.amazonaws.com/jupiter-circleci/test-0.0.1-SNAPSHOT.jar
